### ISSUE TITLE
Decide on coding style

### ISSUE THREAD

**Issue by jonathanKingston** [pauljt/lightbeam-we#9]
As this is a project that mostly @princiya and @biancadanforth will be working on, we should decide on a style and stick to it.

I'm happy to setup the ESLint config of whatever is decided.

Eslint default rules are mostly undisputed the common ones are:

- Tabs / 2 space / 4 space
- Single Quotes, Double Quotes
- Semi colons / Semi colons when needed

I suggest prefer const, async/await wherever possible.

I would also suggest preferring template strings when vars are used also:

```
const me = `Hey ${name}!`;
```

@princiya the initial code @biancadanforth has done suggests her style it seems only fair to let you voice your views.
https://github.com/pauljt/lightbeam-we/blob/master/background.js

**Comment by princiya** [comment]
ESLint preferences:
- Tabs
- Single Quotes
- Semi colons

Looks like these align well with @biancadanforth 's coding style too. 

Also, ES6 wherever possible - const, async/await, template literals etc. 👍

**Comment by princiya** [comment]
Also, we could add a pre-commit ESLint git hook

**Comment by jonathanKingston** [comment]
I had planned to do that today yeah as I'll likely commit spaces and double
quotes otherwise :D

**Comment by jonathanKingston** [comment]
@pauljt I need admin privs or some other special powers to add web hooks.

Under "Collaborators and teams", set me as an admin.

**Comment by biancadanforth** [comment]
My coding style is loosely based off of [AirBnB's JavaScript style guide](http://airbnb.io/javascript/). I do not have strong opinions (yet) about this, so I am flexible and interested in hearing other people's perspectives!

@princiya Would you be open to 2 spaces instead of tabs? Many text editors (like Sublime 3) have a setting that translates a tab as 2 spaces:
`"translate_tabs_to_spaces": true`
so it may not require any change in our tab use. I saw a tab inconsistency in my PR yesterday actually, and I just noticed GitHub interprets tabs at 4 spaces, which looks odd to me! Not a super important detail; I am just curious what your thoughts are.

**Comment by pauljt** [comment]
Tangential note, but I am really digging jsprettier (http://jlongster.com/A-Prettier-Formatter). Its orthogonal to the style we choose, but I love the fact that there are no style decisions that need to be made at all since its all programatic. (e.g. takes care of long function names which cause line breaks etc)
